### ISSUE TITLE
[Bug] Some bosses won't spawn

### ISSUE THREAD

**Issue by MAGNAT2645** [Mentrillum/Slender-Fortress-Modified-Versions#21]
In my case it's `containmentbreach` pack. There's `scp-173.cfg` (notice **lowercase**) config (and its companions).
SF2 logs it like this:
```
L 01/17/2021 - 19:09:28: [disabled/sf2.smx] Loading boss profile files from directory configs/sf2/profiles/packs/containmentbreach...
L 01/17/2021 - 19:09:28: [disabled/sf2.smx] SCP-173...
L 01/17/2021 - 19:09:29: [disabled/sf2.smx] cb_scp049...
L 01/17/2021 - 19:09:29: [disabled/sf2.smx] cb_mtf...
L 01/17/2021 - 19:09:29: [disabled/sf2.smx] Loaded 3 boss profile(s) from directory!
```
(so, it saw profile as in **uppercase**)

I think this might be the problem when SF2 doesn't spawn these bosses (but as i remember you can spawn them manually).
This bug might be with `KeyValues` itself (maybe you should try to use `SMCParser` or even things like [ConfigMap](https://forums.alliedmods.net/showthread.php?t=319763) but this needs a detailed test).

I will rename profile to `cb_scp173.cfg` (and root section in config itself as well), hope it will help.

There's also error:
`Could not select profile for boss 1: profile corruptedjessie is invalid!`
(downloaded from your Wiki)

**Comment by Mentrillum** [comment]
So boss profile names don't count based on the config name, they count based on what the profile name is in the config, for instance, "scp-173" is the profile name for SCP-173. In terms of spawning companions, one of two things can happen when they don't load, either the main boss that spawns the companions cannot find the companions because they aren't in the same pack or don't exist, or the companion boss is there but either a typo was made or a capitalization error was made in the profile name for the companion, which are actually case sensitive. Now as for Corrupted Jessie not loading, if you use KitRifty's new Directory Style loading method, that config file with Corrupted Jessie and Corrupted Woody bundled into it needs to be split up into 2 config files with each profile in both config files, which after Secret Update 8, all existing public Modified bosses that have multiple bosses packed into 1 config should be split up.

**Comment by MAGNAT2645** [comment]
SF2 loads cb pack successfully as seen in log above, all companions and main boss in one same pack.
SF2 logs profiles by their root section name (as i understand), not by display name. Only scp-173.cfg logged as `SCP-173`, that's weird.

**Comment by MAGNAT2645** [comment]
Renaming profile helped. So it was `KeyValues` bug (i don't like to use it in my plugins due to these bugs).

```
Active Boss Indexes:
----------------------------
0 - cb_scp173
1 - cb_mtf
2 - cb_scp049
3 - cb_scp173 (copy of 0)
4 - cb_mtf (copy of 1)
```
