### ISSUE TITLE
Dhooks issue for 1.6.1pre

### ISSUE THREAD

**Issue by medic917** [Mentrillum/Slender-Fortress-Modified-Versions#36]
I was able to compile 1.6.1pre with dhooks-2.2.0-detours16.zip
However, dhooks doesn't seem to load with this version. It did load with dhooks-2.2.0-detours16-sm110.zip but the 110 dhooks doesn't compile with 1.6.1pre.

Do I have to downgrade my sourcemod version as well?

**Comment by medic917** [comment]
Seems to compile with the dhooks sm110 now but server ends up crashing even with the proper dhooks extension and gamedata.

**Comment by medic917** [comment]
Can't compute incursion distances from the Red spawn room(s). Bots will perform poorly. This is caused by either a missing func_respawnroom, or missing info_player_teamspawn entities within the func_respawnroom.
Setting breakpad minidump AppID = 232251
crash_20210626210346_1.dmp[10288]: Uploading dump (out-of-process)
/tmp/dumps/crash_20210626210346_1.dmp

**Comment by Mentrillum** [comment]
"Can't compute incursion distances from the Red spawn room(s). Bots will perform poorly. This is caused by either a missing func_respawnroom, or missing info_player_teamspawn entities within the func_respawnroom." Its a irrelevant error, just tells you the map has no respawn room entity.

Slender Fortress Modified is only supported via Sourcemod 1.10, can't go above or below that version as its no longer being supported on anything but Sourcemod 1.10

**Comment by medic917** [comment]
I am using 1.10 sourcemod but it isnt working still. Could you please upload the smx file for the working version compiled instead of the sp file?

**Comment by Joaquel** [comment]
Did you install all the requirements?
